
import java.awt.Color;
import java.awt.event.*;
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIIT
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */int a=0; 
    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        jButton1.setText("Re!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        l3.setForeground(java.awt.Color.red);
        l3.setText("Press start for locking player names");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(b4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                    .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        t1.setText("Player 1");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Master of X,s");

        l1.setText("Winner:-");

        jLabel2.setText("Master of 0,s");

        t2.setText("Player 2");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        l2.setBackground(new java.awt.Color(50, 49, 221));
        l2.setForeground(java.awt.Color.magenta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(l1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void whoseTurn(){
        if(a%2==0)
            l3.setText(t1.getText()+", go on!");
        else l3.setText(t2.getText()+", your turn!");
    }
    
                                  
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
     if(b1.getText().equals(""))
     {
        if(a%2==0)
        b1.setText("X");
     else
        b1.setText("0"); 
     a++;
     }
     if((b1.getText().equals(b2.getText())&&b2.getText().equals(b3.getText())||b1.getText().equals(b5.getText())&&b5.getText().equals(b9.getText())||b1.getText().equals(b4.getText())&&b4.getText().equals(b7.getText()))&&b1.getText().equals("X"))
     {l2.setText(""+t1.getText());
          if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
     b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");
     }
     else if((b1.getText().equals(b2.getText())&&b2.getText().equals(b3.getText())||b1.getText().equals(b5.getText())&&b5.getText().equals(b9.getText())||b1.getText().equals(b4.getText())&&b4.getText().equals(b7.getText()))&&b1.getText().equals("0"))
     {l2.setText(""+t2.getText());
     if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);
     b1.setText("0");
     b2.setText("0");
     b3.setText("0");
     b4.setText("0");
     b5.setText("0");
     b6.setText("0");
     b7.setText("0");
     b8.setText("0");
     b9.setText("0");
     }
     else if(a==9)
    l2.setText("Draw");
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
      if(b2.getText().equals(""))
      {
        if(a%2==0)
        b2.setText("X");
     else
        b2.setText("0"); 
      a++;}
if((b2.getText().equals(b1.getText())&&b2.getText().equals(b3.getText())||b2.getText().equals(b5.getText())&&b5.getText().equals(b8.getText()))&&b2.getText().equals("X"))
{ l2.setText(""+t1.getText());
     if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");} 
else if((b2.getText().equals(b1.getText())&&b2.getText().equals(b3.getText())||b2.getText().equals(b5.getText())&&b5.getText().equals(b8.getText()))&&b2.getText().equals("0"))
{ l2.setText(""+t2.getText());
     if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);
b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
}
else if(a==9)
    l2.setText("Draw");
// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
if(b3.getText().equals(""))
{
        if(a%2==0)
        b3.setText("X");
     else
        b3.setText("0");  
a++;}
if((b1.getText().equals(b2.getText())&&b2.getText().equals(b3.getText())||b3.getText().equals(b5.getText())&&b5.getText().equals(b7.getText())||b3.getText().equals(b6.getText())&&b6.getText().equals(b9.getText()))&&b3.getText().equals("X"))
{  l2.setText(""+t1.getText());
     if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");
}
     else if((b1.getText().equals(b2.getText())&&b2.getText().equals(b3.getText())||b3.getText().equals(b5.getText())&&b5.getText().equals(b7.getText())||b3.getText().equals(b6.getText())&&b6.getText().equals(b9.getText()))&&b3.getText().equals("0"))
     { l2.setText(""+t2.getText());
         if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);
     b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
     }
else if(a==9)
    l2.setText("Draw");
// TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
if(b4.getText().equals(""))
{
        if(a%2==0)
        b4.setText("X");
     else
        b4.setText("0");
a++;
if((b4.getText().equals(b1.getText())&&b4.getText().equals(b7.getText())||b4.getText().equals(b5.getText())&&b5.getText().equals(b6.getText()))&&b4.getText().equals("X"))
{ l2.setText(""+t1.getText());
     if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");
}
     else if((b4.getText().equals(b1.getText())&&b4.getText().equals(b7.getText())||b4.getText().equals(b5.getText())&&b5.getText().equals(b6.getText()))&&b4.getText().equals("0"))
     { l2.setText(""+t2.getText());
         if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);
     b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
     }
else if(a==9)
    l2.setText("Draw");
// TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed
    }
    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
     if(b5.getText().equals(""))
     {
        if(a%2==0)
        b5.setText("X");
     else
        b5.setText("0"); 
a++;
if((b5.getText().equals(b2.getText())&&b2.getText().equals(b8.getText())||b5.getText().equals(b4.getText())&&b5.getText().equals(b6.getText())||b5.getText().equals(b3.getText())&&b7.getText().equals(b5.getText()))&&b5.getText().equals("X"))
{ l2.setText(""+t1.getText());
     if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");
}
     else if((b5.getText().equals(b2.getText())&&b2.getText().equals(b8.getText())||b5.getText().equals(b4.getText())&&b5.getText().equals(b6.getText()))&&b5.getText().equals("0"))
     { l2.setText(""+t2.getText());
          if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);
     b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
     }
     else if(a==9)
    l2.setText("Draw");
// TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed
    }
    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
if(b6.getText().equals(""))
{   if(a%2==0)
        b6.setText("X");
     else
        b6.setText("0"); 
a++;
if((b6.getText().equals(b3.getText())&&b6.getText().equals(b9.getText())||b6.getText().equals(b5.getText())&&b5.getText().equals(b4.getText()))&&b6.getText().equals("X"))
{  l2.setText(""+t1.getText());
     if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");
}
     else if((b6.getText().equals(b3.getText())&&b6.getText().equals(b9.getText())||b6.getText().equals(b5.getText())&&b5.getText().equals(b4.getText()))&&b6.getText().equals("0"))
     {  l2.setText(""+t2.getText());
    
          if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
     }
     else if(a==9)
    l2.setText("Draw");
// TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed
    }
    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
if(b7.getText().equals(""))
{   if(a%2==0)
        b7.setText("X");
     else
        b7.setText("0"); 
a++;
if((b7.getText().equals(b8.getText())&&b7.getText().equals(b9.getText())||b7.getText().equals(b5.getText())&&b5.getText().equals(b3.getText())||b1.getText().equals(b4.getText())&&b4.getText().equals(b7.getText()))&&b7.getText().equals("X"))
{   l2.setText(""+t1.getText());
     if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");
}
     else if((b7.getText().equals(b8.getText())&&b7.getText().equals(b9.getText())||b7.getText().equals(b5.getText())&&b5.getText().equals(b3.getText())||b1.getText().equals(b4.getText())&&b4.getText().equals(b7.getText()))&&b7.getText().equals("0"))
     { l2.setText(""+t2.getText());
          if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);
     b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
     }
     else if(a==9)
    l2.setText("Draw");// TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed
    }
    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
     if(b8.getText().equals(""))
     {
        if(a%2==0)
        b8.setText("X");
     else
        b8.setText("0");
       a++;
if((b7.getText().equals(b8.getText())&&b7.getText().equals(b9.getText())||b8.getText().equals(b5.getText())&&b5.getText().equals(b2.getText()))&&b8.getText().equals("X"))
{l2.setText(""+t1.getText());
     if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");
}
     else if((b7.getText().equals(b8.getText())&&b7.getText().equals(b9.getText())||b8.getText().equals(b5.getText())&&b5.getText().equals(b2.getText()))&&b8.getText().equals("0"))
     {     l2.setText(""+t2.getText());
          if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);
     b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
     }
     else if(a==9)
    l2.setText("Draw");// TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed
    }
    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
if(b9.getText().equals(""))
{   if(a%2==0)
        b9.setText("X");
     else
        b9.setText("0");
a++;
if((b9.getText().equals(b8.getText())&&b8.getText().equals(b7.getText())||b1.getText().equals(b5.getText())&&b5.getText().equals(b9.getText())||b9.getText().equals(b6.getText())&&b6.getText().equals(b3.getText()))&&b9.getText().equals("X"))
{   
    l2.setText(""+t1.getText());
         if(b1.getText().equals("X"))b1.setBackground(Color.blue);
     if(b2.getText().equals("X"))b2.setBackground(Color.blue);
     if(b3.getText().equals("X"))b3.setBackground(Color.blue);
     if(b4.getText().equals("X"))b4.setBackground(Color.blue);
     if(b5.getText().equals("X"))b5.setBackground(Color.blue);
     if(b6.getText().equals("X"))b6.setBackground(Color.blue);
     if(b7.getText().equals("X"))b7.setBackground(Color.blue);
     if(b8.getText().equals("X"))b8.setBackground(Color.blue);
     if(b9.getText().equals("X"))b9.setBackground(Color.blue);
     if(b1.getText().equals("0"))b1.setBackground(Color.red);
     if(b2.getText().equals("0"))b2.setBackground(Color.red);
     if(b3.getText().equals("0"))b3.setBackground(Color.red);
     if(b4.getText().equals("0"))b4.setBackground(Color.red);
     if(b5.getText().equals("0"))b5.setBackground(Color.red);
     if(b6.getText().equals("0"))b6.setBackground(Color.red);
     if(b7.getText().equals("0"))b7.setBackground(Color.red);
     if(b8.getText().equals("0"))b8.setBackground(Color.red);
     if(b9.getText().equals("0"))b9.setBackground(Color.red);
    b1.setText("X");
    b2.setText("X");
    b3.setText("X");
    b4.setText("X");
    b5.setText("X");
    b6.setText("X");
    b7.setText("X");
    b8.setText("X");
    b9.setText("X");
} 
    else if((b9.getText().equals(b8.getText())&&b8.getText().equals(b7.getText())||b1.getText().equals(b5.getText())&&b5.getText().equals(b9.getText())||b9.getText().equals(b6.getText())&&b6.getText().equals(b3.getText()))&&b9.getText().equals("0"))
    { l2.setText(""+t2.getText());
         if(b1.getText().equals("0"))b1.setBackground(Color.blue);
     if(b2.getText().equals("0"))b2.setBackground(Color.blue);
     if(b3.getText().equals("0"))b3.setBackground(Color.blue);
     if(b4.getText().equals("0"))b4.setBackground(Color.blue);
     if(b5.getText().equals("0"))b5.setBackground(Color.blue);
     if(b6.getText().equals("0"))b6.setBackground(Color.blue);
     if(b7.getText().equals("0"))b7.setBackground(Color.blue);
     if(b8.getText().equals("0"))b8.setBackground(Color.blue);
     if(b9.getText().equals("0"))b9.setBackground(Color.blue);
     if(b1.getText().equals("X"))b1.setBackground(Color.red);
     if(b2.getText().equals("X"))b2.setBackground(Color.red);
     if(b3.getText().equals("X"))b3.setBackground(Color.red);
     if(b4.getText().equals("X"))b4.setBackground(Color.red);
     if(b5.getText().equals("X"))b5.setBackground(Color.red);
     if(b6.getText().equals("X"))b6.setBackground(Color.red);
     if(b7.getText().equals("X"))b7.setBackground(Color.red);
     if(b8.getText().equals("X"))b8.setBackground(Color.red);
     if(b9.getText().equals("X"))b9.setBackground(Color.red);
    b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
    
    }
     else if(a==9)
    l2.setText("Draw");
    }//GEN-LAST:event_b9ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        a=0;
       b1.setText("");
       b2.setText("");
       b3.setText("");
       b4.setText("");
       b5.setText("");
       b6.setText("");
       b7.setText("");
       b8.setText("");
       b9.setText("");
       l2.setText("");
         b1.setBackground(Color.white);
         b2.setBackground(Color.white);
         b3.setBackground(Color.white);
         b4.setBackground(Color.white);
         b5.setBackground(Color.white);
         b6.setBackground(Color.white);
         b7.setBackground(Color.white);
         b8.setBackground(Color.white);
         b9.setBackground(Color.white);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        l3.setText("");
        t1.setEditable(false);
        t2.setEditable(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}